
on:
  schedule:
  - cron: '*/15 * * * *'
  push:
    branches: [ "main" ]

jobs:
  stale-issue:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        days-before-issue-stale: 1
        days-before-pr-close: 2
        stale-issue-message: 'Stale issue message'
        stale-issue-label: 'stale issue!'
        
  Check-OS-and-list-files:
    
    runs-on: ubuntu-latest
    steps:
      - name: Version of operating system
        run: lsb_release -a
      - uses: actions/checkout@v3
      - name: Checkout code and list files
        run: ls

       
